---
version: 2
jobs:
  release:
    docker:
      - image: node:latest
    working_directory: ~/cli
    steps:
      - add_ssh_keys
      - checkout
      - restore_cache: &restore_cache
          keys:
            - v0-yarn-{{checksum ".circleci/config.yml"}}-{{ .Branch }}-{{checksum "yarn.lock"}}
            - v0-yarn-{{checksum ".circleci/config.yml"}}-{{ .Branch }}-
            - v0-yarn-{{checksum ".circleci/config.yml"}}-master-
      - run: yarn
      - run: yarn test
      - run: .circleci/release
      - save_cache: &save_cache
          key: v0-yarn-{{checksum ".circleci/config.yml"}}-{{ .Branch }}-{{checksum "yarn.lock"}}
          paths:
            - ~/cli/node_modules
            - /usr/local/share/.cache/yarn
            - /usr/local/share/.config/yarn

workflows:
  version: 2
  "@oclif/semantic-release":
    jobs:
      - release
